#![allow(dead_code)]

use alloy::{
    genesis::Genesis,
    primitives::{Address, Bytes, TxKind, U256, address},
    sol_types::SolValue,
};
use alloy_evm::{Evm, EvmEnv, EvmFactory};
use alloy_rlp::Encodable;
use eyre::{WrapErr as _, eyre};
use revm::{
    DatabaseCommit,
    context::{
        TxEnv,
        result::{ExecutionResult, Output},
    },
    database::{CacheDB, EmptyDB},
    state::AccountInfo,
};
use tempo_chainspec::hardfork::TempoHardfork;
use tempo_evm::evm::{TempoEvm, TempoEvmFactory};
use tempo_primitives::TempoHeader;
use tempo_revm::{TempoBlockEnv, TempoTxEnv};

pub(crate) const TEMPO_STATE_ADDRESS: Address =
    address!("0x1c00000000000000000000000000000000000000");
pub(crate) const ZONE_INBOX_ADDRESS: Address =
    address!("0x1c00000000000000000000000000000000000001");
pub(crate) const ZONE_OUTBOX_ADDRESS: Address =
    address!("0x1c00000000000000000000000000000000000002");
pub(crate) const ZONE_CONFIG_ADDRESS: Address =
    address!("0x1c00000000000000000000000000000000000003");

const DEPLOYER: Address = address!("0xdeadbeefdeadbeefdeadbeefdeadbeefdeadbeef");

pub(crate) type TestEvm = TempoEvm<CacheDB<EmptyDB>>;

#[derive(serde::Deserialize)]
struct FoundryArtifact {
    bytecode: BytecodeField,
}

#[derive(serde::Deserialize)]
struct BytecodeField {
    object: String,
}

pub(crate) fn base_zone_test_genesis() -> eyre::Result<Genesis> {
    serde_json::from_str(include_str!("assets/zone-test-genesis.json"))
        .wrap_err("valid zone test genesis")
}

/// Fill the zone system contract bytecode from freshly compiled Foundry artifacts.
///
/// This keeps `zone-test-genesis.json` free of checked-in bytecode blobs while
/// still preserving the fixture's storage and non-system predeploy entries.
/// If constructor-initialized storage changes, the fixture storage still needs
/// to be regenerated because this helper only refreshes deployed runtime code.
/// Contracts are deployed through the EVM so Solidity immutables are baked into
/// runtime code by their constructors instead of patched by byte offset.
pub(crate) fn patch_genesis_with_compiled_system_contracts(
    genesis: &mut Genesis,
    chain_id: u64,
    tempo_portal: Address,
) -> eyre::Result<()> {
    let mut header_rlp = Vec::new();
    TempoHeader::default().encode(&mut header_rlp);
    let mut evm = setup_zone_evm_with_contracts_for_portal(chain_id, tempo_portal, header_rlp)?;

    for (name, addr) in [
        ("TempoState", TEMPO_STATE_ADDRESS),
        ("ZoneConfig", ZONE_CONFIG_ADDRESS),
        ("ZoneInbox", ZONE_INBOX_ADDRESS),
        ("ZoneOutbox", ZONE_OUTBOX_ADDRESS),
    ] {
        let account = evm
            .db_mut()
            .cache
            .accounts
            .get(&addr)
            .ok_or_else(|| eyre!("{name} missing from generated EVM state"))?;
        let code = account
            .info
            .code
            .as_ref()
            .ok_or_else(|| eyre!("{name} has no generated bytecode"))?
            .original_bytes();

        let genesis_account = genesis
            .alloc
            .get_mut(&addr)
            .ok_or_else(|| eyre!("{name} missing from zone test genesis at {addr:#x}"))?;
        genesis_account.code = Some(code);
        genesis_account.nonce = Some(account.info.nonce);
    }

    Ok(())
}

/// Build an EVM with the zone system contracts deployed in memory.
///
/// This mirrors the genesis-generation flow used by tests: load creation
/// bytecode from `specs/ref-impls/out`, run constructors with the requested
/// portal and Tempo genesis header, then relocate deployed runtime accounts to
/// their fixed zone predeploy addresses.
pub(crate) fn setup_zone_evm_with_contracts_for_portal(
    chain_id: u64,
    tempo_portal: Address,
    tempo_genesis_header_rlp: Vec<u8>,
) -> eyre::Result<TestEvm> {
    let gas_limit = 30_000_000u64;

    let db = CacheDB::default();
    let mut env: EvmEnv<TempoHardfork, TempoBlockEnv> =
        EvmEnv::default().with_timestamp(U256::ZERO);
    env.cfg_env.chain_id = chain_id;
    env.cfg_env.tx_gas_limit_cap = Some(u64::MAX);
    env.block_env.inner.gas_limit = gas_limit;

    let factory = TempoEvmFactory::default();
    let mut evm = factory.create_evm(db, env);

    evm.db_mut().insert_account_info(
        DEPLOYER,
        AccountInfo {
            balance: U256::from(1_000_000_000_000_000_000_000u128),
            ..Default::default()
        },
    );

    let specs_out =
        std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../../specs/ref-impls/out");
    let mut nonce = 0u64;

    let tempo_state_bytecode = load_artifact(&specs_out, "TempoState")?;
    let tempo_state_args = (Bytes::from(tempo_genesis_header_rlp),).abi_encode_params();
    deploy_contract(
        &mut evm,
        &tempo_state_bytecode,
        &tempo_state_args,
        TEMPO_STATE_ADDRESS,
        "TempoState",
        chain_id,
        nonce,
    )?;
    nonce += 1;

    let zone_config_bytecode = load_artifact(&specs_out, "ZoneConfig")?;
    let zone_config_args = (tempo_portal, TEMPO_STATE_ADDRESS).abi_encode_params();
    deploy_contract(
        &mut evm,
        &zone_config_bytecode,
        &zone_config_args,
        ZONE_CONFIG_ADDRESS,
        "ZoneConfig",
        chain_id,
        nonce,
    )?;
    nonce += 1;

    let zone_inbox_bytecode = load_artifact(&specs_out, "ZoneInbox")?;
    let zone_inbox_args =
        (ZONE_CONFIG_ADDRESS, tempo_portal, TEMPO_STATE_ADDRESS).abi_encode_params();
    deploy_contract(
        &mut evm,
        &zone_inbox_bytecode,
        &zone_inbox_args,
        ZONE_INBOX_ADDRESS,
        "ZoneInbox",
        chain_id,
        nonce,
    )?;
    nonce += 1;

    let zone_outbox_bytecode = load_artifact(&specs_out, "ZoneOutbox")?;
    let zone_outbox_args = (ZONE_CONFIG_ADDRESS,).abi_encode_params();
    deploy_contract(
        &mut evm,
        &zone_outbox_bytecode,
        &zone_outbox_args,
        ZONE_OUTBOX_ADDRESS,
        "ZoneOutbox",
        chain_id,
        nonce,
    )?;

    Ok(evm)
}

/// Load a Foundry artifact's creation bytecode from the specs output directory.
fn load_artifact(specs_out: &std::path::Path, name: &str) -> eyre::Result<Vec<u8>> {
    let path = specs_out
        .join(format!("{name}.sol"))
        .join(format!("{name}.json"));
    let content = std::fs::read_to_string(&path)
        .wrap_err_with(|| format!("failed to read artifact at `{}`", path.display()))?;
    let artifact: FoundryArtifact = serde_json::from_str(&content)
        .wrap_err_with(|| format!("failed to parse artifact at `{}`", path.display()))?;
    const_hex::decode(&artifact.bytecode.object)
        .wrap_err_with(|| format!("failed to decode {name} bytecode hex"))
}

/// Deploy a contract into the CacheDB via the EVM, then relocate it to the predeploy address.
fn deploy_contract(
    evm: &mut TestEvm,
    creation_bytecode: &[u8],
    constructor_args: &[u8],
    predeploy_addr: Address,
    name: &str,
    chain_id: u64,
    nonce: u64,
) -> eyre::Result<()> {
    let mut initcode = Vec::with_capacity(creation_bytecode.len() + constructor_args.len());
    initcode.extend_from_slice(creation_bytecode);
    initcode.extend_from_slice(constructor_args);

    let tx = TempoTxEnv {
        inner: TxEnv {
            caller: DEPLOYER,
            gas_price: 0,
            gas_limit: 30_000_000,
            kind: TxKind::Create,
            data: initcode.into(),
            chain_id: Some(chain_id),
            nonce,
            ..Default::default()
        },
        ..Default::default()
    };

    let result = evm
        .transact_raw(tx)
        .map_err(|e| eyre!("{name} deployment tx failed: {e:?}"))?;
    let created_addr = match &result.result {
        ExecutionResult::Success { output, .. } => match output {
            Output::Create(_, Some(addr)) => *addr,
            _ => return Err(eyre!("{name} deployment did not return a created address")),
        },
        ExecutionResult::Revert { output, .. } => {
            return Err(eyre!("{name} deployment reverted: {output}"));
        }
        ExecutionResult::Halt { reason, .. } => {
            return Err(eyre!("{name} deployment halted: {reason:?}"));
        }
    };

    evm.db_mut().commit(result.state);

    let db = evm.db_mut();
    if let Some(mut created_account) = db.cache.accounts.remove(&created_addr) {
        created_account.info.nonce = 1;
        db.cache.accounts.insert(predeploy_addr, created_account);
        Ok(())
    } else {
        Err(eyre!(
            "{name} deployed to {created_addr} but account not found in CacheDB"
        ))
    }
}
